version: '2'
services:
  atrix-pubsub:
    build:
      context: .
      args:
        - NPM_TOKEN=${NPM_TOKEN}
    image: trigo/atrix-pubsub:latest
    command: 'yarn run test'
    environment:
      - TEST_REDIS=redis
      - ATRIX_PUBSUB_DATASOURCE_M1_CONFIG_REDIS_HOST=redis
      - ATRIX_PUBSUB_DATASOURCE_M1_CONFIG_QUEUENAME=pubsub-test
      - NODE_ENV=test
      - NPM_TOKEN
      - I_WANT_TEST_LOGGING=1
    networks:
      - atrix-pubsub_test
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - atrix-pubsub_test

networks:
  atrix-pubsub_test:
    driver: bridge
