version: '2'
services:
  redis:
    image: redis
    networks:
      - atrix-pubsub_test
    ports:
      - 6379:6379

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - atrix-pubsub_test
    ports:
      - 5672:5672
      - 15672:15672

networks:
  atrix-pubsub_test:
    driver: bridge
